# Saber SkyBlock by: Trent #

#        Saber SkyBlock Commands & Permissions List          #
#       https://docs.google.com/document/d/12fwGgU35YeNu8Iu8LPHXqZyNfrpGX0htTdaK3vRWhAg/edit      #
#   /is - Main Island Command  #
#   /isa - Admin Island Commands ( permission: isa.admin ) #

messages:
  is-help:
    - '   &b&lSavage SkyBlock  &bHelp'
    - ''
    - '&a  /is &8-&7 opens the island Panel'
    - '&a  /is help &8-&7 displays this message.'
    - '&a  /is spawn &8-&7 teleports you to spawn.'
    - '&a  /is invite <player> &8-&7 invite a player to the island'
    - '&a  /is join|accept &8&- join a island'
    - '&a  /is promote <player>'
    - '&a  /is kick <player>'
    - '&a  /is demote <player>'
    - '&a  /is verison'
    - '&a  /is worth'
    - '&a  /is top'
    - '&a  /is perms'
    - '&a  /is home'
    - '&a  /is create'
    - '&a  /is biome'
    - '&a  /is delete'
    - '&a  /is sethome'

  isa-help: # is admin help
    - '   &b&lSavage SkyBlock &bAdmin Help'
    - ''
    - '&a  /isa &8-&7 displays these messages'
    - '&a  /isa setspawn &8-&7 sets the SkyBlock spawn.'
    - '&a  /isa reload'
    - '&a  /isa delete <player>'
    - ''

  reload: '&aReloaded the config.yml and the prices.yml files!'

  ##########################################################################################
  #This is the island message section
  createIsland: '&aYou have created an island!'
  alreadyIsland: '&aYou are already in an island!'
  notYours: '&aCannot break/place in this island!'
  deleteIsland: '&cYou have deleted your island!'
  deletedIsland: '&aThe island you were on has been deleted!'
  notInIsland: '&cYou are not a member of an island!'
  notOwner: '&cYou are not the owner of the island!'
  cancelDeleting: '&aYou have canceled your deleting!'
  setPermission: '&aYou have updated &9%role%&a''s permission for &9%type%&a to &d%outcome%&a!'
  noIsland: '&aYou do not have an Island!'
  ##########################################################################################

  ##########################################################################################
  #This is the teleporting/spawn message section
  teleportSpawn: '&aTeleported to Spawn!'
  teleportHome: '&aTeleported to your island''s home!'
  setSpawn: '&aYou have set the island Spawn to this location!'
  setHome: '&aYou have set your island''s home to this location!'
  noSpawn: '&cThe Administrators have not set an island Spawn yet!'
  ##########################################################################################

  ##########################################################################################
  #This is the permission message section
  noPermission: '&cYou do not have permissions for this command!'
  noPermissionBiome: '&cYou do not have permissions for this biome!'
  invalidBiome: '&cThis biome is invalid!'
  noIslandPermissionCreate: '&aYou do not have permission to create this type of island!'
  noPermissionKick: '&aYou do not have permission to kick this player!'
  noPlayer: '&aPlease run the command with a player argument!'
  noIslandArg: '&aPlease run the command with an island argument!'
  forceDelete: '&aYour island has been forcefully deleted!'
  forceDeleteDeleter: '&aYou have forcefully deleted this player''s island!!'

  noPermissionIsland: '&aYou do not have permissions to use this command in the island!'
  setBiome: '&aYou have set the biome!'
  ##########################################################################################

  ##########################################################################################
  #This is the island roles section
  promotedOwner: '&aYou have promoted &b%player%&a to Owner of the island!'
  promotedOwnerMe: '&aYou have been promoted to the Owner of the island!'
  promotedOfficer: '&aYou have promoted &b%player%&a to an Officer of the island!'
  promotedOfficerMe: '&aYou have been promoted to an Officer in the island!'
  promotedNoPlayer: '&aThis player is not in your island!'
  cannotPromoteDemoteSelf: '&aYou cannot promote/demote yourself!'
  demotedNo: '&aYou cannot demote this player any lower than they already are!'
  demotedNoPlayer: '&aThis player is not in your island!'
  demotedMember: '&aYou have demoted &b%player%&a back to a member!'
  demotedMemberMe: '&aYou have been demoted back to a member!'
  demoted: '&aYou have demoted &b%player%&a from being an Officer in the island!'
  demotedMe: '&aYou have been demoted from Officer in the island!'
  ##########################################################################################

  ##########################################################################################
  #This is the island kick messages section
  kicked: '&aYou have kicked &b%player% &afrom the island!'
  kickedMe: '&aYou have been kicked from the island!'
  kickedYourself: '&aYou cannot kick yourself!'
  kickedNoPlayer: '&aThis player is not in your island!'
  ##########################################################################################

  ##########################################################################################
  #This is the island invite message section
  alreadyInvited: '&aThis player is already invited to your island!'
  invited: '&aYou have been invited to &b%player%&a''s island!'
  invitedMe: '&aYou have invited &b%player%&ato the island!'
  inviteExpire: '&bThe invite to &a%player%&b''s island has expired!'
  inviterNotInIsland: '&aThis player is not in an island!'
  notInvited: '&aYou are not invited into this island!'
  ##########################################################################################

  ##########################################################################################
  #This is the island join message section
  joined: '&aYou have joined this island!'
  couldNotJoin: '&aSomething happened and you could not join this island! Report to the Administrators! (ERROR CODE: 1)'
  left: '&aYou have left this island!'
  ##########################################################################################

  ##########################################################################################
  # Island Misc message section
  placeblockRestriction: '&cYou cannot build outside your Island''s protection range!'
  breakblockRestriction: '&cYou cannot break outside your Island''s protection range!'
  hopper-limit: '&cYou cannot place anymore hoppers on this island!'
  spawner-limit: '&cYou cannot place anymore spawners on this island!'

  upgrade_purchased: '&8&l(&c&l!&8&l) &aUpgraded &l%upgrade%&a to tier &b&l%tier%&a!'
  upgrade_denied: '&8&l(&c&l!&8&l) &cError, not enough money for this upgrade!'
  upgrade_max: '&8&l(&c&l!&8&l) &cThis upgrade is already &lMaxed&c!'

  upgrade_purchased_everyone: '&8&l(&c&l!&8&l) &e%player% &aupgraded &l%upgrade%&a to tier &b&l%tier%&a!'
  ##########################################################################################

  ##########################################################################################
  # IS-TOP sections
  is-worth:
    - '&b&m----------------------'
    - ''
    - '&aIsland: &b{island-name}'
    - '&aIsland Level: &b{island-level}'
    - '&aIsland Top: &b{island-top}'
    - ''
    - '&b&m----------------------'
  starting-calculations:
    - '&7&m----------------------'
    - '&aStarting IS-TOP Calculations...'
    - '&7&m----------------------'
  completed-calculations:
    - '&7&m----------------------'
    - '&aCompleted IS-TOP Calculations!'
    - '&7&m----------------------'
  ##########################################################################################

settings:

  disable-fallDamage: true # no fall damage? yes.

  island-fly-permission: 'skyblock.fly' # allows flying on THEIR own Island

  default-hopper-limit: 5 # override with permission: skyblock.block.anvil.NUMBER
  default-spawner-limit: 5 # override with permission: skyblock.block.spawner.NUMBER
  default-member-limit: 5 # override with permission: skyblock.members.NUMBER, permission overrides Upgrade
  default-protection-radius: 50 # 50^4, block radius around each corner of island, override with permission: skyblock.protection.NUMBER

  island-level-calculation-time: 60 # in seconds
  island-level-placeholder: '%is-level%' # can use this in chat formatting
  broadcast-isTop-calculations: true

  invalid-island-top-name-placeholders: '&cInvalid Island'
  invalid-island-top-lore-placeholders: '&c&lN/A'

  use-chat-format: true
  chat-format: '&a{is-level} &7[&9{is-top}&7] &r{old-format}'

  min-x: 0 # the starting point on the x axis to start plotting islands
  min-z: 0 # the starting point on the z axis to start plotting islands
  max-x: 1000 # the ending point on the x axis to stop plotting islands
  max-z: 1000 # the ending point on the z axis to stop plotting islands

  default-biome: 'PLAINS'
  inviteExpireTime: 10 # seconds

  island-spawn: 'not-set' # set using /isa setspawn