name: SaberSkyBlock
authors:
  - Driftay
  - Trent
version: 1.5
api-version: 1.13
main: me.saber.skyblock.Main
depend:
  - WorldEdit
  - Vault
commands:
  is:
    aliases:
      - island
  sbp:
    aliases:
      - skyblockplus