name: SavageSkyBlock
authors:
  - Trent
version: '1.3'

main: org.savage.skyblock.SkyBlock

depend:
  - WorldEdit
  - Vault
  - Essentials

softdepend:
  - WildStacker
  - Votifier

load: POSTWORLD

commands:
  is:
    aliases:
      - island
  isa:
    aliases:
      - isadmin