name: SavageSkyBlock
authors:
  - Driftay
  - Trent
version: 1.2
main: org.savage.skyblock.Main
depend:
  - WorldEdit
  - Vault
commands:
  is:
    aliases:
      - island
  isa:
    aliases:
      - isadmin